// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
///<reference types="node"/>
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error('Database Url not defined in env file');
}
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});
